<?php
/**
	array(
		'业务模块名'=>array(
					'host'=>'redis服务host，默认127.0.0.1',
					'port'=>'redis端口,默认6379',
					'database'=>redis数据库号默认0,
					'prefix'=>'该组业务redis-key前缀，注意业务前缀不要跟其它模块的prefix前缀同名，默认无',
					'desc'=>'业务描述，可填项',
			),
		'pay'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>0,
					'prefix'=>'aaz:pay:',
			),

	);

*/
return array(
			'pay'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>0,
					'prefix'=>'aaz:pay:',
					'desc'=>'支付模块业务'
			),
			'auth'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:auth:',
					'desc'=>'登录认证模块'
			),
			'user'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>2,
					'prefix'=>'aaz:user:',
					'desc'=>'用户信息模块'
			),
			'house'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>3,
					'prefix'=>'aaz:house:',
					'desc'=>'房源模块'
			),
			'global'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>4,
					'prefix'=>'aaz:global:',
					'desc'=>'全局通用配置模块，各个仓库共用'
			),
			'misc'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:global:',
					'desc'=>'不好归类通通放这个模块'
			),
			'weixin'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:wx:',
					'desc'=>'微信业务模块'
			),
			'admin'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:admin:',
					'desc'=>'后台业务模块'
			),
			'api'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:api:',
					'desc'=>'api仓库独有业务模块'
			),
			'pc'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:pc:',
					'desc'=>'pc网站独有业务模块'
			),
			'h5'=>array(
					'host'=>'10.59.72.31',
					'port'=>'6379',
					'database'=>1,
					'prefix'=>'aaz:h5:',
					'desc'=>'h5触屏网站独有业务模块'
			),

);